name: mlflow-env

channels:
  - conda-forge

dependencies:
  - python=3.12.7
  - pip<=25.2
  - pip:
      - mlflow==3.4.0
      - cloudpickle==3.1.1
      - numpy==2.1.2          # versi stabil & compatible dengan py3.12
      - pandas==2.2.3         # versi terbaru yg support py3.12
      - psutil==7.1.0
      - pyarrow==17.0.0       # versi lebih stabil untuk py3.12
      - scikit-learn==1.5.2   # versi kompatibel & stabil
      - scipy==1.14.1         # versi terbaru yg support py3.12
